### ISSUE TITLE
How to enable Ingress?

### ISSUE THREAD

**Issue by SuperJMN** [pajikos/home-assistant-helm-chart#29]
Hi! I'm trying to enable Ingress in my release.
I'm trying with: 

```bash
helm upgrade home-assistant pajikos/home-assistant --set ingress.enabled=true,ingress.hosts={"192.168.1.29"},persistence.enabled=true,persistence.storageClass=seaweedfs-storage
```

But I get this error:

```bash
Error: UPGRADE FAILED: template: home-assistant/templates/ingress.yaml:41:15: executing "home-assistant/templates/ingress.yaml" at <.host>: can't evaluate field host in type interface {}
```

Note: 192.168.1.29 is the IP of the cluster node where the Home Assistant pod is running.

Thanks a lot!

**Comment by pajikos** [comment]
Hi,
try this:
```bash
helm upgrade home-assistant pajikos/home-assistant \
  --set ingress.enabled=true \
  --set "ingress.hosts[0].host=192.168.1.29" \
  --set persistence.enabled=true \
  --set persistence.storageClass=seaweedfs-storage
```

Setting ingress.hosts={"192.168.1.29"}  sets the entire ingress.hosts field to the string "{192.168.1.29}" as a single item list. This is different from setting the first item in the list to "192.168.1.29".

Usually, there is no need to set IP addresses in an ingress but may depend on the selected ingress controller.

Regards

**Comment by pajikos** [comment]
Hi, have you solved this issue?
