### ISSUE TITLE
A request from a reverse proxy was received from <IP>, but your HTTP integration is not set-up for reverse proxies

### ISSUE THREAD

**Issue by jjacobsson** [pajikos/home-assistant-helm-chart#53]
Hi! 

This is probably a case of rtfm. I am seeing the following in my logs:

`<date & time> ERROR (MainThread) [homeassistant.components.http.forwarded] A request from a reverse proxy was received from <IP>, but your HTTP integration is not set-up for reverse proxies`

I am using a nginx ingress, when I try to access the service I get `400: Bad Request`.

Googling tells me I need to configure home assistant to trust the reverse proxy in home assistants configuration. I can figure out _what_ I need to put into Home Assistants configuration, but I can't figure out _how_ to get it there . I _guess_ I somehow do that with one or more of the values for the chart? podAnotations? Enviroment variables? Something else? I can't really see how, an example would be most welcome!

**Comment by jjacobsson** [comment]
Oh, I found the configuration.yaml in my PVC... I guess I can just edit that....

**Comment by pajikos** [comment]
#30 trying to solve here

**Comment by jjacobsson** [comment]
Yeah saw that issue after writing this one :D Silly of me! Sorry for the spam!
