### ISSUE TITLE
README updates for adding a zigbee device

### ISSUE THREAD

**Issue by gammons** [pajikos/home-assistant-helm-chart#56]
Hi there, this helm chart is great.  I had a lot of trouble adding a zigbee device using the chart, however.  

I think it should be more clear that you need to set `securityContext.privileged` to `true`.  While it does say that in the README, this particular setting is not part of the values.yaml table.  So I was using `podSecurityContext`, which is not correct.  Let me know if it makes sense to update the README a bit to reflect that, and I'd be happy to submit a PR.

**Comment by pajikos** [comment]
Hi @gammons, readme contains notes about this requirement (https://github.com/pajikos/home-assistant-helm-chart#additional-volumes-and-volume-mounts), but you are welcome to make any update to make it more clear how to connect a zigbee device.
Thanks
