### ISSUE TITLE
Expose dnsPolicy setting

### ISSUE THREAD

**Issue by ghjklw** [pajikos/home-assistant-helm-chart#69]
Hi,

Would it be possible to expose the pod's [dnsPolicy](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy) setting just like dnsConfig? This is particularly relevant when hostNetwork is set to True:

> For Pods running with hostNetwork, you should explicitly set its DNS policy to "ClusterFirstWithHostNet". Otherwise, Pods running with hostNetwork and "ClusterFirst" will fallback to the behavior of the "Default" policy.

**Comment by pajikos** [comment]
resolved by #68
