### ISSUE TITLE
Best practise to install HACS

### ISSUE THREAD

**Issue by iptizer** [pajikos/home-assistant-helm-chart#77]
I would like to have HACS installed on the home-assistant running this chart.

Please correct me if I am wrong. I see two options:
* Customizing the docker image with HACS pre-installed.
* Building this into an init container.

Would be cool to get someones opinion, happy to provide a PR to the docs with and example afterwards.

Maybe there is even a way easier way that I did not stumble opon until now.

**Comment by iptizer** [comment]
Feedback is still very welcome. I discovered that this could be added directly to the init script. But it requires installation of bash.

In essence, add the following lines [here](https://github.com/pajikos/home-assistant-helm-chart/blob/main/charts/home-assistant/values.yaml#L244)

```
    # install hacs - see https://www.hacs.xyz/docs/use/download/download/#to-download-hacs
    apk add --no-cache bash
    wget -O - https://get.hacs.xyz | bash -
```

**Comment by pajikos** [comment]
Hi, I checked the installation script. I think running it in an init container would be sufficient. HACS is installing to the config directory, so it would be quite challenging to make the image with HACS preinstalled. 

It would be fine to make it optional, similar to creating a config directory as you can see in the current version of the Helm chart.

**Comment by ncasaux** [comment]
> Hey, I read this thread and followed your advise by creating an init container:
> 
> ```
> initContainers:
>   - name: init-hacs
>     image: bash
>     command: ["bash", "-c", "cd /config && wget -O - https://get.hacs.xyz | bash -"]
>     volumeMounts:
>       - mountPath: /config
>         name: home-assistant
> ```
> 
> This worked for me, hope it helps others.

Thanks for this!
