### ISSUE TITLE
Add support for configuring ServiceAccount for HomeAssistant

### ISSUE THREAD

**Issue by 98jan** [pajikos/home-assistant-helm-chart#84]
Hi,

I isntalled your Helm Chart in my Kubernetes Environment and added a few CiliumNetworkPolicies with the created serviceAccount (can be linked to a serviceAccount).
 I could use the "default" serviceAccount, but I want to have a dedicated one configured for homeassistant only (e.g. code-server would use the same one).
But then I saw that only the creation of the ServiceAccount is there but no logic that the configured serviceAccount is added to the StatefulSet manifest.

Could you provide that functionality or can I create a PR to add support for it?

My values.yaml for serviceAccount

```
    serviceAccount:
      name: homeassistant
```

The statefulset configuration that is missing:
```
spec:
  template:
    spec:
      serviceAccountName: <serviceAccountName>
```

**Comment by pajikos** [comment]
Hi @98jan, you’re absolutely correct—this is indeed a bug. The logic to apply the specified serviceAccount to the StatefulSet manifest is missing. You’re very welcome to submit a PR to add this functionality, thanks.

**Comment by 98jan** [comment]
just created a PR, that links the serviceAccount if create is set to true and if name is empty the fallback value is used, if name is set the name is used.

Please review and give me feedback if anything is missing.
